# Generated by Django 2.2.5 on 2019-10-09 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factura', '0001_initial'),
        ('producto', '0001_initial'),
        ('detalle_factura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_factura',
            name='id_factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Factura'),
        ),
        migrations.AddField(
            model_name='detalle_factura',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
    ]
