# Generated by Django 2.2.5 on 2019-10-09 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro_proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id_kardex', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_factura', models.DateField()),
                ('num_factura', models.IntegerField()),
                ('serie_factura', models.CharField(max_length=20)),
                ('tipo_operacion', models.BooleanField()),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_proveedores.Proveedor')),
            ],
        ),
    ]
