# Generated by Django 2.2.5 on 2019-10-09 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('cod_producto', models.CharField(max_length=45)),
                ('nom_producto', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=150)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.Categoria')),
            ],
        ),
    ]
