# Generated by Django 2.2.5 on 2019-10-09 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puesto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('dpi', models.CharField(max_length=15)),
                ('id_puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puesto.Puesto')),
            ],
        ),
    ]
